[[redirects]]
  from = "/"
  to = "/sales"
  status = 200
  force = false
  conditions = {Role = ["sales"]}

[[redirects]]
  from = "/"
  to = "/recruiting"
  status = 200
  force = false
  conditions = {Role = ["recruiting"]}
